x-service-templates:
  api: &api
    build:
      context: ./api
      dockerfile: Dockerfile.dev # DEV
    env_file:
      - .env
    volumes:
      - ./api:/var/www/html # DEV
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "25MB"

services:

  loadbalancer:
    container_name: loadbalancer
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
    depends_on:
      - api1
      - api2

  api1:
    <<: *api
    container_name: api1

  api2:
    <<: *api
    container_name: api2

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      # Comentando volume para que o banco seja criado sempre que subir o container
      # - database-data:/var/lib/postgresql/data
      - ./database/src:/scripts/src # DEV
      - ./database/install:/scripts/install # DEV
      - ./database/update:/scripts/update # DEV
      - ./database/update.sh:/scripts/update.sh # DEV
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
