x-service-templates:
  api: &api
    build:
      context: ./api
      dockerfile: Dockerfile.dev # DEV
    env_file:
      - .env
    volumes:
      - ./api:/var/www/html # DEV
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "25MB"

services:

  loadbalancer:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
    depends_on:
      - api1
      - api2

  api1:
    <<: *api

  api2:
    <<: *api

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
